# Generated by Django 4.1.7 on 2023-03-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOffices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=1024)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('pesel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('A', 'Admin'), ('D', 'Dentist'), ('R', 'Receptionist')], max_length=128)),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.branchoffices')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('service', models.CharField(max_length=512)),
                ('visit_time', models.TimeField()),
                ('branch_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.branchoffices')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.personel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.patients')),
            ],
        ),
    ]
