# Generated by Django 4.1.7 on 2023-03-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dentist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personel",
            name="branch_office",
        ),
        migrations.AlterField(
            model_name="personel",
            name="role",
            field=models.CharField(
                choices=[("R", "Receptionist"), ("A", "Admin"), ("D", "Dentist")],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="visits",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "D"},
                on_delete=django.db.models.deletion.CASCADE,
                to="dentist.personel",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personel",
            name="branch_office",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="dentist.branchoffices"
            ),
        ),
    ]
