# Generated by Django 4.1.7 on 2023-03-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dentist", "0002_remove_personel_branch_office_alter_personel_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personel",
            name="role",
            field=models.CharField(
                choices=[("A", "Admin"), ("D", "Dentist"), ("R", "Receptionist")],
                max_length=128,
            ),
        ),
    ]
